services:
  insights-api:
    build:
      context: ./insights-service
      dockerfile: Dockerfile.dev
    container_name: insights-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - ./insights-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - spice-network
    command: npm run dev

  spice-webapp:
    build:
      context: ./spice-webapp
      dockerfile: Dockerfile.dev
    container_name: spice-webapp
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - .env.dev
    volumes:
      - ./spice-webapp:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - insights-api
    networks:
      - spice-network
    command: npm run dev

  mongodb:
    image: mongo:7.0
    container_name: spice-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env.dev
    volumes:
      - mongodb_data:/data/db
    networks:
      - spice-network

volumes:
  mongodb_data:

networks:
  spice-network:
    driver: bridge